baseURL: "https://theme.scientific-python.org/"
languageCode: "en-us"
title: "Test Website"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  description: "Sandbox for testing crowdin integration with a hugo site."
  images:
    - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Test Website
    link: /
  hero:
    title: Test Website
    image: logo.svg
  navbar:
    - title: Section 1
      url: /section1/
    - title: Section 2
      url: /section2/
    - title: Section 3
      url: /section3/
  keyfeatures:
    features:
      - title: Crowdin Integration
        text: Integrated with [Crowdin](https://crowdin.com)
      - title: Test Website
        text: This is just a test site.
      - title: Stuff
        text: Some stuff goes here.
  footer:
    logo: logo.svg
    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /about/
          - text: Spam
            link: https://en.wikipedia.org/wiki/Spam_(food)
      column2:
        links:
          - text: Spam
            link: https://en.wikipedia.org/wiki/Spam_(Monty_Python_sketch)
      column3:
        links:
