cd reproject_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  - source: /content/en/*.yaml
    translation: /content/%two_letters_code%/%original_file_name%
  - source: /content/en/*.md
    translation: /content/%two_letters_code%/%original_file_name%
  - source /content/en/about/*.md
    translation /content/%two_letters_code%/%original_file_name%
  - source /content/en/news/*.md
    translation /content/%two_letters_code%/%original_file_name%