languageName: Español
params:
  description: "Área de pruebas para probar la integración de Crowdin con un sitio Hugo."
  images:
    - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Sitio web de pruebas
    link: /
  hero:
    title: Sitio web de pruebas
    image: logo.svg
  keyfeatures:
    features:
      - 
        title: Integración de Crowdin
        text: Integrado con [Crowdin](https://crowdin.com)
      - 
        title: Sitio web de pruebas
        text: Este es solo un sitio de prueba.
      - 
        title: Cosas
        text: Algunas cosas van aquí.
navbar:
  - 
    title: Sección 1
    url: /section1/
  - 
    title: Sección 2
    url: /section2/
  - 
    title: Sección 3
    url: /section3/
footer:
  logo: logo.svg
  quicklinks:
    column1:
      title: ""
      links:
        - 
          text: Sobre
          link: /about/
        - 
          text: Spam
          link: https://en.wikipedia.org/wiki/Spam_(food)
    column2:
      links:
        - 
          text: Spam
          link: https://en.wikipedia.org/wiki/Spam_(Monty_Python_sketch)
    column3:
      links:
